"""
This module provides a class that defines the API endpoints available for Rapid7 InsightVM API v3.
"""

class InsightVMAPIv3Endpoints:
    """
    A class that defines the API endpoints available for Rapid7 InsightVM API v3.
    """
    ASSET_GROUP = "asset-group"
    ASSET = "asset"
    AUTHENTICATION = "authentication"
    CONFIGURATION = "configuration"
    CREDENTIAL = "credential"
    DISCOVERY_CONNECTION = "discovery-connection"
    DISCOVERY_PROFILE = "discovery-profile"
    ENGINE = "engine"
    EXPORT = "export"
    IMPORT = "import"
    LICENSE = "license"
    REPORT = "report"
    ROLE = "role"
    SCAN = "scan"
    SITE = "site"
    TAG = "tag"
    USER = "user"
    VULNERABILITY_EXCEPTION = "vulnerability-exception"
    VULNERABILITY = "vulnerability"
    VULNERABILITY_CHECK = "vulnerability-check"
    VULNERABILITY_DEFINITION = "vulnerability-definition"
    VULNERABILITY_SOLUTION = "vulnerability-solution"
